### ISSUE TITLE
PROVIDER: Tag (read description!)

### ISSUE THREAD

**Issue by hannahnier** [MindfulStudio/frontend#232]
!attention: There is a component called TagsContext that has nothing to do with a provider!

**Comment by nadjascodejourney** [comment]
@hannahnier 
@barisbalcimusic 
@luisePkt 

TagsContext is the component, where the tags for the category "context" are displayed.
("Womit könnte dein Gefühl in Verbindung gestanden haben")

We can rename it, for example:
- ContextualTags - Indicates that these are tags related to a specific context or situation
- TagsFurtherAssociations - Indicates, that these are the tags with further associations

Open for other suggestions! :-)
